# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ec2-ami-backup
  description: Terraform module for automatic & scheduled AMI creation
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, aws, aws-lambda, ami, scheduled-events, backups, cronjob, snapshot, ebs
